package com.thienloc.model;

public class Accounts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.user_name
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.active
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	private Boolean active;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.encryted_password
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	private String encrytedPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.user_role
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	private String userRole;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.user_name
	 * @return  the value of accounts.user_name
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.user_name
	 * @param userName  the value for accounts.user_name
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.active
	 * @return  the value of accounts.active
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.active
	 * @param active  the value for accounts.active
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.encryted_password
	 * @return  the value of accounts.encryted_password
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	public String getEncrytedPassword() {
		return encrytedPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.encryted_password
	 * @param encrytedPassword  the value for accounts.encryted_password
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	public void setEncrytedPassword(String encrytedPassword) {
		this.encrytedPassword = encrytedPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.user_role
	 * @return  the value of accounts.user_role
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	public String getUserRole() {
		return userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.user_role
	 * @param userRole  the value for accounts.user_role
	 * @mbg.generated  Fri Sep 16 09:52:07 ICT 2022
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}
}