package com.thienloc.model;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blog_id
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title_code
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private String titleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.name
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content_type
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private String contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.size
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.display
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private Integer display;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.created_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.updated_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.deleted_flag
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private Integer deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.deleted_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    private Date deletedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_id
     *
     * @return the value of blog.blog_id
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_id
     *
     * @param blogId the value for blog.blog_id
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title_code
     *
     * @return the value of blog.title_code
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public String getTitleCode() {
        return titleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title_code
     *
     * @param titleCode the value for blog.title_code
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setTitleCode(String titleCode) {
        this.titleCode = titleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.name
     *
     * @return the value of blog.name
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.name
     *
     * @param name the value for blog.name
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content_type
     *
     * @return the value of blog.content_type
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content_type
     *
     * @param contentType the value for blog.content_type
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.size
     *
     * @return the value of blog.size
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.size
     *
     * @param size the value for blog.size
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.display
     *
     * @return the value of blog.display
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public Integer getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.display
     *
     * @param display the value for blog.display
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setDisplay(Integer display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.created_date
     *
     * @return the value of blog.created_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.created_date
     *
     * @param createdDate the value for blog.created_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.updated_date
     *
     * @return the value of blog.updated_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.updated_date
     *
     * @param updatedDate the value for blog.updated_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.deleted_flag
     *
     * @return the value of blog.deleted_flag
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public Integer getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.deleted_flag
     *
     * @param deletedFlag the value for blog.deleted_flag
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setDeletedFlag(Integer deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.deleted_date
     *
     * @return the value of blog.deleted_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public Date getDeletedDate() {
        return deletedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.deleted_date
     *
     * @param deletedDate the value for blog.deleted_date
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    public void setDeletedDate(Date deletedDate) {
        this.deletedDate = deletedDate;
    }
}