package com.thienloc.model;

import java.util.Date;

public class Category {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.category_id
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Long categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.category_type
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Integer categoryType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.category_parent_id
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Long categoryParentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.category_code
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private String categoryCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.category_name
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private String categoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.sort
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.created_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.updated_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Date updatedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.deleted_flag
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Integer deletedFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.deleted_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Date deletedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.display
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	private Integer display;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.category_id
	 * @return  the value of category.category_id
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_id
	 * @param categoryId  the value for category.category_id
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.category_type
	 * @return  the value of category.category_type
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Integer getCategoryType() {
		return categoryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_type
	 * @param categoryType  the value for category.category_type
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setCategoryType(Integer categoryType) {
		this.categoryType = categoryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.category_parent_id
	 * @return  the value of category.category_parent_id
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Long getCategoryParentId() {
		return categoryParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_parent_id
	 * @param categoryParentId  the value for category.category_parent_id
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setCategoryParentId(Long categoryParentId) {
		this.categoryParentId = categoryParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.category_code
	 * @return  the value of category.category_code
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public String getCategoryCode() {
		return categoryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_code
	 * @param categoryCode  the value for category.category_code
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.category_name
	 * @return  the value of category.category_name
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_name
	 * @param categoryName  the value for category.category_name
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.sort
	 * @return  the value of category.sort
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.sort
	 * @param sort  the value for category.sort
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.created_date
	 * @return  the value of category.created_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.created_date
	 * @param createdDate  the value for category.created_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.updated_date
	 * @return  the value of category.updated_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.updated_date
	 * @param updatedDate  the value for category.updated_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.deleted_flag
	 * @return  the value of category.deleted_flag
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Integer getDeletedFlag() {
		return deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.deleted_flag
	 * @param deletedFlag  the value for category.deleted_flag
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setDeletedFlag(Integer deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.deleted_date
	 * @return  the value of category.deleted_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Date getDeletedDate() {
		return deletedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.deleted_date
	 * @param deletedDate  the value for category.deleted_date
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.display
	 * @return  the value of category.display
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Integer getDisplay() {
		return display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.display
	 * @param display  the value for category.display
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setDisplay(Integer display) {
		this.display = display;
	}
}