package com.thienloc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CategoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public CategoryExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCategoryIdIsNull() {
			addCriterion("category_id is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNotNull() {
			addCriterion("category_id is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdEqualTo(Long value) {
			addCriterion("category_id =", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotEqualTo(Long value) {
			addCriterion("category_id <>", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThan(Long value) {
			addCriterion("category_id >", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
			addCriterion("category_id >=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThan(Long value) {
			addCriterion("category_id <", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
			addCriterion("category_id <=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIn(List<Long> values) {
			addCriterion("category_id in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotIn(List<Long> values) {
			addCriterion("category_id not in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdBetween(Long value1, Long value2) {
			addCriterion("category_id between", value1, value2, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
			addCriterion("category_id not between", value1, value2, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeIsNull() {
			addCriterion("category_type is null");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeIsNotNull() {
			addCriterion("category_type is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeEqualTo(Integer value) {
			addCriterion("category_type =", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeNotEqualTo(Integer value) {
			addCriterion("category_type <>", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeGreaterThan(Integer value) {
			addCriterion("category_type >", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("category_type >=", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeLessThan(Integer value) {
			addCriterion("category_type <", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeLessThanOrEqualTo(Integer value) {
			addCriterion("category_type <=", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeIn(List<Integer> values) {
			addCriterion("category_type in", values, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeNotIn(List<Integer> values) {
			addCriterion("category_type not in", values, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeBetween(Integer value1, Integer value2) {
			addCriterion("category_type between", value1, value2, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("category_type not between", value1, value2, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdIsNull() {
			addCriterion("category_parent_id is null");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdIsNotNull() {
			addCriterion("category_parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdEqualTo(Long value) {
			addCriterion("category_parent_id =", value, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdNotEqualTo(Long value) {
			addCriterion("category_parent_id <>", value, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdGreaterThan(Long value) {
			addCriterion("category_parent_id >", value, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("category_parent_id >=", value, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdLessThan(Long value) {
			addCriterion("category_parent_id <", value, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdLessThanOrEqualTo(Long value) {
			addCriterion("category_parent_id <=", value, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdIn(List<Long> values) {
			addCriterion("category_parent_id in", values, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdNotIn(List<Long> values) {
			addCriterion("category_parent_id not in", values, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdBetween(Long value1, Long value2) {
			addCriterion("category_parent_id between", value1, value2, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryParentIdNotBetween(Long value1, Long value2) {
			addCriterion("category_parent_id not between", value1, value2, "categoryParentId");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeIsNull() {
			addCriterion("category_code is null");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeIsNotNull() {
			addCriterion("category_code is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeEqualTo(String value) {
			addCriterion("category_code =", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeNotEqualTo(String value) {
			addCriterion("category_code <>", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeGreaterThan(String value) {
			addCriterion("category_code >", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeGreaterThanOrEqualTo(String value) {
			addCriterion("category_code >=", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeLessThan(String value) {
			addCriterion("category_code <", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeLessThanOrEqualTo(String value) {
			addCriterion("category_code <=", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeLike(String value) {
			addCriterion("category_code like", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeNotLike(String value) {
			addCriterion("category_code not like", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeIn(List<String> values) {
			addCriterion("category_code in", values, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeNotIn(List<String> values) {
			addCriterion("category_code not in", values, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeBetween(String value1, String value2) {
			addCriterion("category_code between", value1, value2, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeNotBetween(String value1, String value2) {
			addCriterion("category_code not between", value1, value2, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIsNull() {
			addCriterion("category_name is null");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIsNotNull() {
			addCriterion("category_name is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryNameEqualTo(String value) {
			addCriterion("category_name =", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotEqualTo(String value) {
			addCriterion("category_name <>", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameGreaterThan(String value) {
			addCriterion("category_name >", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
			addCriterion("category_name >=", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLessThan(String value) {
			addCriterion("category_name <", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLessThanOrEqualTo(String value) {
			addCriterion("category_name <=", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLike(String value) {
			addCriterion("category_name like", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotLike(String value) {
			addCriterion("category_name not like", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIn(List<String> values) {
			addCriterion("category_name in", values, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotIn(List<String> values) {
			addCriterion("category_name not in", values, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameBetween(String value1, String value2) {
			addCriterion("category_name between", value1, value2, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotBetween(String value1, String value2) {
			addCriterion("category_name not between", value1, value2, "categoryName");
			return (Criteria) this;
		}

		public Criteria andSortIsNull() {
			addCriterion("sort is null");
			return (Criteria) this;
		}

		public Criteria andSortIsNotNull() {
			addCriterion("sort is not null");
			return (Criteria) this;
		}

		public Criteria andSortEqualTo(Integer value) {
			addCriterion("sort =", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotEqualTo(Integer value) {
			addCriterion("sort <>", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThan(Integer value) {
			addCriterion("sort >", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("sort >=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThan(Integer value) {
			addCriterion("sort <", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThanOrEqualTo(Integer value) {
			addCriterion("sort <=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortIn(List<Integer> values) {
			addCriterion("sort in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotIn(List<Integer> values) {
			addCriterion("sort not in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortBetween(Integer value1, Integer value2) {
			addCriterion("sort between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotBetween(Integer value1, Integer value2) {
			addCriterion("sort not between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIsNull() {
			addCriterion("created_date is null");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIsNotNull() {
			addCriterion("created_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedDateEqualTo(Date value) {
			addCriterion("created_date =", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotEqualTo(Date value) {
			addCriterion("created_date <>", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateGreaterThan(Date value) {
			addCriterion("created_date >", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("created_date >=", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateLessThan(Date value) {
			addCriterion("created_date <", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
			addCriterion("created_date <=", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIn(List<Date> values) {
			addCriterion("created_date in", values, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotIn(List<Date> values) {
			addCriterion("created_date not in", values, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateBetween(Date value1, Date value2) {
			addCriterion("created_date between", value1, value2, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
			addCriterion("created_date not between", value1, value2, "createdDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateIsNull() {
			addCriterion("updated_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateIsNotNull() {
			addCriterion("updated_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateEqualTo(Date value) {
			addCriterion("updated_date =", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateNotEqualTo(Date value) {
			addCriterion("updated_date <>", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateGreaterThan(Date value) {
			addCriterion("updated_date >", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_date >=", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateLessThan(Date value) {
			addCriterion("updated_date <", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
			addCriterion("updated_date <=", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateIn(List<Date> values) {
			addCriterion("updated_date in", values, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateNotIn(List<Date> values) {
			addCriterion("updated_date not in", values, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateBetween(Date value1, Date value2) {
			addCriterion("updated_date between", value1, value2, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
			addCriterion("updated_date not between", value1, value2, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagIsNull() {
			addCriterion("deleted_flag is null");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagIsNotNull() {
			addCriterion("deleted_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagEqualTo(Integer value) {
			addCriterion("deleted_flag =", value, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagNotEqualTo(Integer value) {
			addCriterion("deleted_flag <>", value, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagGreaterThan(Integer value) {
			addCriterion("deleted_flag >", value, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("deleted_flag >=", value, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagLessThan(Integer value) {
			addCriterion("deleted_flag <", value, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagLessThanOrEqualTo(Integer value) {
			addCriterion("deleted_flag <=", value, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagIn(List<Integer> values) {
			addCriterion("deleted_flag in", values, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagNotIn(List<Integer> values) {
			addCriterion("deleted_flag not in", values, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagBetween(Integer value1, Integer value2) {
			addCriterion("deleted_flag between", value1, value2, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("deleted_flag not between", value1, value2, "deletedFlag");
			return (Criteria) this;
		}

		public Criteria andDeletedDateIsNull() {
			addCriterion("deleted_date is null");
			return (Criteria) this;
		}

		public Criteria andDeletedDateIsNotNull() {
			addCriterion("deleted_date is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedDateEqualTo(Date value) {
			addCriterion("deleted_date =", value, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateNotEqualTo(Date value) {
			addCriterion("deleted_date <>", value, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateGreaterThan(Date value) {
			addCriterion("deleted_date >", value, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("deleted_date >=", value, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateLessThan(Date value) {
			addCriterion("deleted_date <", value, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateLessThanOrEqualTo(Date value) {
			addCriterion("deleted_date <=", value, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateIn(List<Date> values) {
			addCriterion("deleted_date in", values, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateNotIn(List<Date> values) {
			addCriterion("deleted_date not in", values, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateBetween(Date value1, Date value2) {
			addCriterion("deleted_date between", value1, value2, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDeletedDateNotBetween(Date value1, Date value2) {
			addCriterion("deleted_date not between", value1, value2, "deletedDate");
			return (Criteria) this;
		}

		public Criteria andDisplayIsNull() {
			addCriterion("display is null");
			return (Criteria) this;
		}

		public Criteria andDisplayIsNotNull() {
			addCriterion("display is not null");
			return (Criteria) this;
		}

		public Criteria andDisplayEqualTo(Integer value) {
			addCriterion("display =", value, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayNotEqualTo(Integer value) {
			addCriterion("display <>", value, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayGreaterThan(Integer value) {
			addCriterion("display >", value, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayGreaterThanOrEqualTo(Integer value) {
			addCriterion("display >=", value, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayLessThan(Integer value) {
			addCriterion("display <", value, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayLessThanOrEqualTo(Integer value) {
			addCriterion("display <=", value, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayIn(List<Integer> values) {
			addCriterion("display in", values, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayNotIn(List<Integer> values) {
			addCriterion("display not in", values, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayBetween(Integer value1, Integer value2) {
			addCriterion("display between", value1, value2, "display");
			return (Criteria) this;
		}

		public Criteria andDisplayNotBetween(Integer value1, Integer value2) {
			addCriterion("display not between", value1, value2, "display");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table category
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 20 22:39:35 ICT 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}