package com.thienloc.model;

public class ImageProductKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image_product.product_id
	 * @mbg.generated  Wed Aug 31 21:21:35 ICT 2022
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image_product.image_id
	 * @mbg.generated  Wed Aug 31 21:21:35 ICT 2022
	 */
	private Long imageId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image_product.product_id
	 * @return  the value of image_product.product_id
	 * @mbg.generated  Wed Aug 31 21:21:35 ICT 2022
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image_product.product_id
	 * @param productId  the value for image_product.product_id
	 * @mbg.generated  Wed Aug 31 21:21:35 ICT 2022
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image_product.image_id
	 * @return  the value of image_product.image_id
	 * @mbg.generated  Wed Aug 31 21:21:35 ICT 2022
	 */
	public Long getImageId() {
		return imageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image_product.image_id
	 * @param imageId  the value for image_product.image_id
	 * @mbg.generated  Wed Aug 31 21:21:35 ICT 2022
	 */
	public void setImageId(Long imageId) {
		this.imageId = imageId;
	}
}