package com.thienloc.model;

import java.util.Date;

public class ImagesBanner {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images_banner.image_type
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	private Integer imageType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images_banner.image_name
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	private String imageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images_banner.content_type
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	private String contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images_banner.size
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	private Long size;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images_banner.width
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	private Integer width;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images_banner.height
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	private Integer height;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images_banner.created_date
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images_banner.updated_date
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	private Date updatedDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images_banner.image_type
	 * @return  the value of images_banner.image_type
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public Integer getImageType() {
		return imageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images_banner.image_type
	 * @param imageType  the value for images_banner.image_type
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public void setImageType(Integer imageType) {
		this.imageType = imageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images_banner.image_name
	 * @return  the value of images_banner.image_name
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public String getImageName() {
		return imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images_banner.image_name
	 * @param imageName  the value for images_banner.image_name
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images_banner.content_type
	 * @return  the value of images_banner.content_type
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images_banner.content_type
	 * @param contentType  the value for images_banner.content_type
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images_banner.size
	 * @return  the value of images_banner.size
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public Long getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images_banner.size
	 * @param size  the value for images_banner.size
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public void setSize(Long size) {
		this.size = size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images_banner.width
	 * @return  the value of images_banner.width
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public Integer getWidth() {
		return width;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images_banner.width
	 * @param width  the value for images_banner.width
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public void setWidth(Integer width) {
		this.width = width;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images_banner.height
	 * @return  the value of images_banner.height
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public Integer getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images_banner.height
	 * @param height  the value for images_banner.height
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public void setHeight(Integer height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images_banner.created_date
	 * @return  the value of images_banner.created_date
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images_banner.created_date
	 * @param createdDate  the value for images_banner.created_date
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images_banner.updated_date
	 * @return  the value of images_banner.updated_date
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images_banner.updated_date
	 * @param updatedDate  the value for images_banner.updated_date
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}