package com.thienloc.model;

public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.order_detail_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    private Long orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.amount
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.price
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.quanity
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    private Integer quanity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.order_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.product_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    private Long productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.order_detail_id
     *
     * @return the value of order_details.order_detail_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.order_detail_id
     *
     * @param orderDetailId the value for order_details.order_detail_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.amount
     *
     * @return the value of order_details.amount
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.amount
     *
     * @param amount the value for order_details.amount
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.price
     *
     * @return the value of order_details.price
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.price
     *
     * @param price the value for order_details.price
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.quanity
     *
     * @return the value of order_details.quanity
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public Integer getQuanity() {
        return quanity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.quanity
     *
     * @param quanity the value for order_details.quanity
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public void setQuanity(Integer quanity) {
        this.quanity = quanity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.order_id
     *
     * @return the value of order_details.order_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.order_id
     *
     * @param orderId the value for order_details.order_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.product_id
     *
     * @return the value of order_details.product_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.product_id
     *
     * @param productId the value for order_details.product_id
     *
     * @mbg.generated Fri Aug 12 21:05:48 ICT 2022
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }
}