package com.thienloc.model;

import java.util.Date;

public class Orders {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.order_id
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.total_price
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private Long totalPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.total_product
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private Integer totalProduct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.customer_name
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private String customerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.customer_address_1
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private String customerAddress1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.customer_address_2
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private String customerAddress2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.customer_email
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private String customerEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.customer_phone
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private String customerPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.note
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.method_pay
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private Integer methodPay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.order_date
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private Date orderDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.status
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.updated_date
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	private Date updatedDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.order_id
	 * @return  the value of orders.order_id
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.order_id
	 * @param orderId  the value for orders.order_id
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.total_price
	 * @return  the value of orders.total_price
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public Long getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.total_price
	 * @param totalPrice  the value for orders.total_price
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setTotalPrice(Long totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.total_product
	 * @return  the value of orders.total_product
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public Integer getTotalProduct() {
		return totalProduct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.total_product
	 * @param totalProduct  the value for orders.total_product
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setTotalProduct(Integer totalProduct) {
		this.totalProduct = totalProduct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.customer_name
	 * @return  the value of orders.customer_name
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.customer_name
	 * @param customerName  the value for orders.customer_name
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.customer_address_1
	 * @return  the value of orders.customer_address_1
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public String getCustomerAddress1() {
		return customerAddress1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.customer_address_1
	 * @param customerAddress1  the value for orders.customer_address_1
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setCustomerAddress1(String customerAddress1) {
		this.customerAddress1 = customerAddress1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.customer_address_2
	 * @return  the value of orders.customer_address_2
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public String getCustomerAddress2() {
		return customerAddress2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.customer_address_2
	 * @param customerAddress2  the value for orders.customer_address_2
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setCustomerAddress2(String customerAddress2) {
		this.customerAddress2 = customerAddress2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.customer_email
	 * @return  the value of orders.customer_email
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public String getCustomerEmail() {
		return customerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.customer_email
	 * @param customerEmail  the value for orders.customer_email
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.customer_phone
	 * @return  the value of orders.customer_phone
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public String getCustomerPhone() {
		return customerPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.customer_phone
	 * @param customerPhone  the value for orders.customer_phone
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.note
	 * @return  the value of orders.note
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.note
	 * @param note  the value for orders.note
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.method_pay
	 * @return  the value of orders.method_pay
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public Integer getMethodPay() {
		return methodPay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.method_pay
	 * @param methodPay  the value for orders.method_pay
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setMethodPay(Integer methodPay) {
		this.methodPay = methodPay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.order_date
	 * @return  the value of orders.order_date
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public Date getOrderDate() {
		return orderDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.order_date
	 * @param orderDate  the value for orders.order_date
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.status
	 * @return  the value of orders.status
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.status
	 * @param status  the value for orders.status
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.updated_date
	 * @return  the value of orders.updated_date
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.updated_date
	 * @param updatedDate  the value for orders.updated_date
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}