package com.thienloc.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_price
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private Long totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_product
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private Integer totalProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.customer_name
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.customer_address
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private String customerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.customer_email
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private String customerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.customer_phone
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private String customerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.note
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.method_pay
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private Integer methodPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_date
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_price
     *
     * @return the value of order.total_price
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public Long getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_price
     *
     * @param totalPrice the value for order.total_price
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_product
     *
     * @return the value of order.total_product
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public Integer getTotalProduct() {
        return totalProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_product
     *
     * @param totalProduct the value for order.total_product
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setTotalProduct(Integer totalProduct) {
        this.totalProduct = totalProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.customer_name
     *
     * @return the value of order.customer_name
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.customer_name
     *
     * @param customerName the value for order.customer_name
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.customer_address
     *
     * @return the value of order.customer_address
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.customer_address
     *
     * @param customerAddress the value for order.customer_address
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.customer_email
     *
     * @return the value of order.customer_email
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.customer_email
     *
     * @param customerEmail the value for order.customer_email
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.customer_phone
     *
     * @return the value of order.customer_phone
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.customer_phone
     *
     * @param customerPhone the value for order.customer_phone
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.note
     *
     * @return the value of order.note
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.note
     *
     * @param note the value for order.note
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.method_pay
     *
     * @return the value of order.method_pay
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public Integer getMethodPay() {
        return methodPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.method_pay
     *
     * @param methodPay the value for order.method_pay
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setMethodPay(Integer methodPay) {
        this.methodPay = methodPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_date
     *
     * @return the value of order.order_date
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_date
     *
     * @param orderDate the value for order.order_date
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Tue Sep 06 08:45:04 ICT 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}