package com.thienloc.model;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_id
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_name
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_code
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private String productCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.category_id
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Long categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.price
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.promotion_flag
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Integer promotionFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.promotion_price
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Long promotionPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.brand
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private String brand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.description
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.detail
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private String detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.info
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private String info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.quantity
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.top_view
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Integer topView;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.display
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Integer display;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.created_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updated_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Date updatedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.deleted_flag
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Integer deletedFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.deleted_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Date deletedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.image_name
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private String imageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.content_type
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private String contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.size
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	private Long size;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_id
	 * @return  the value of product.product_id
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_id
	 * @param productId  the value for product.product_id
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_name
	 * @return  the value of product.product_name
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_name
	 * @param productName  the value for product.product_name
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_code
	 * @return  the value of product.product_code
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public String getProductCode() {
		return productCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_code
	 * @param productCode  the value for product.product_code
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.category_id
	 * @return  the value of product.category_id
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.category_id
	 * @param categoryId  the value for product.category_id
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.price
	 * @return  the value of product.price
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.price
	 * @param price  the value for product.price
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.promotion_flag
	 * @return  the value of product.promotion_flag
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Integer getPromotionFlag() {
		return promotionFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.promotion_flag
	 * @param promotionFlag  the value for product.promotion_flag
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setPromotionFlag(Integer promotionFlag) {
		this.promotionFlag = promotionFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.promotion_price
	 * @return  the value of product.promotion_price
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Long getPromotionPrice() {
		return promotionPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.promotion_price
	 * @param promotionPrice  the value for product.promotion_price
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setPromotionPrice(Long promotionPrice) {
		this.promotionPrice = promotionPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.brand
	 * @return  the value of product.brand
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.brand
	 * @param brand  the value for product.brand
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setBrand(String brand) {
		this.brand = brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.description
	 * @return  the value of product.description
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.description
	 * @param description  the value for product.description
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.detail
	 * @return  the value of product.detail
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.detail
	 * @param detail  the value for product.detail
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.info
	 * @return  the value of product.info
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.info
	 * @param info  the value for product.info
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setInfo(String info) {
		this.info = info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.quantity
	 * @return  the value of product.quantity
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.quantity
	 * @param quantity  the value for product.quantity
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.top_view
	 * @return  the value of product.top_view
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Integer getTopView() {
		return topView;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.top_view
	 * @param topView  the value for product.top_view
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setTopView(Integer topView) {
		this.topView = topView;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.display
	 * @return  the value of product.display
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Integer getDisplay() {
		return display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.display
	 * @param display  the value for product.display
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setDisplay(Integer display) {
		this.display = display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.created_date
	 * @return  the value of product.created_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.created_date
	 * @param createdDate  the value for product.created_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updated_date
	 * @return  the value of product.updated_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updated_date
	 * @param updatedDate  the value for product.updated_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.deleted_flag
	 * @return  the value of product.deleted_flag
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Integer getDeletedFlag() {
		return deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.deleted_flag
	 * @param deletedFlag  the value for product.deleted_flag
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setDeletedFlag(Integer deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.deleted_date
	 * @return  the value of product.deleted_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Date getDeletedDate() {
		return deletedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.deleted_date
	 * @param deletedDate  the value for product.deleted_date
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.image_name
	 * @return  the value of product.image_name
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public String getImageName() {
		return imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.image_name
	 * @param imageName  the value for product.image_name
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.content_type
	 * @return  the value of product.content_type
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.content_type
	 * @param contentType  the value for product.content_type
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.size
	 * @return  the value of product.size
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public Long getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.size
	 * @param size  the value for product.size
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	public void setSize(Long size) {
		this.size = size;
	}
}