package com.thienloc.mapper;

import com.thienloc.model.Blog;
import com.thienloc.model.BlogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    long countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    int deleteByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    int insert(Blog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    int insertSelective(Blog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    Blog selectByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Blog row, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    int updateByExample(@Param("row") Blog row, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    int updateByPrimaryKeySelective(Blog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Sun Aug 28 11:10:30 ICT 2022
     */
    int updateByPrimaryKey(Blog row);
}