package com.thienloc.mapper;

import com.thienloc.model.Category;
import com.thienloc.model.CategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	long countByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	int deleteByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	int deleteByPrimaryKey(Long categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	int insert(Category row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	int insertSelective(Category row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	List<Category> selectByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	Category selectByPrimaryKey(Long categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Category row, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	int updateByExample(@Param("row") Category row, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	int updateByPrimaryKeySelective(Category row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Sun Sep 04 16:29:06 ICT 2022
	 */
	int updateByPrimaryKey(Category row);
}