package com.thienloc.mapper;

import com.thienloc.model.ImagesBanner;
import com.thienloc.model.ImagesBannerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ImagesBannerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	long countByExample(ImagesBannerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	int deleteByExample(ImagesBannerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	int deleteByPrimaryKey(Integer imageType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	int insert(ImagesBanner row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	int insertSelective(ImagesBanner row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	List<ImagesBanner> selectByExample(ImagesBannerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	ImagesBanner selectByPrimaryKey(Integer imageType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") ImagesBanner row, @Param("example") ImagesBannerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	int updateByExample(@Param("row") ImagesBanner row, @Param("example") ImagesBannerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	int updateByPrimaryKeySelective(ImagesBanner row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images_banner
	 * @mbg.generated  Thu Sep 15 22:15:43 ICT 2022
	 */
	int updateByPrimaryKey(ImagesBanner row);
}