package com.thienloc.mapper;

import com.thienloc.model.Orders;
import com.thienloc.model.OrdersExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrdersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	long countByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	int deleteByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	int insert(Orders row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	int insertSelective(Orders row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	List<Orders> selectByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	Orders selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Orders row, @Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	int updateByExample(@Param("row") Orders row, @Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	int updateByPrimaryKeySelective(Orders row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Sep 14 17:01:35 ICT 2022
	 */
	int updateByPrimaryKey(Orders row);
}