package com.thienloc.mapper;

import com.thienloc.form.ProductForm;
import com.thienloc.model.Product;
import com.thienloc.model.ProductExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	long countByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	int deleteByPrimaryKey(Long productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	int insert(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	int insertSelective(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	List<Product> selectByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	Product selectByPrimaryKey(Long productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Product row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	int updateByExample(@Param("row") Product row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	int updateByPrimaryKeySelective(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Sep 05 17:35:52 ICT 2022
	 */
	int updateByPrimaryKey(Product row);

	ProductForm selectByProductId(@Param(value = "productId") Long productId);
    
    List<ProductForm> selectAll(@Param(value = "promotionFlag") Integer promotionFlag, @Param(value = "orderBy") String orderBy, @Param(value = "sort") String sort, @Param(value = "displayFlag") Integer displayFlag, @Param(value = "topViewFlag") Integer topViewFlag, @Param(value = "brandName") String brandName);
    
    List<ProductForm> selectAllByCategoryId(@Param(value = "categoryIdList") List<Long> categoryIdList, @Param(value = "orderBy") String orderBy, @Param(value = "sort") String sort, @Param(value = "displayFlag") Integer displayFlag, @Param(value = "limitFlag") Integer limitFlag);

    List<ProductForm> selectBySearchKey(@Param(value = "orderBy") String orderBy, @Param(value = "sort") String sort, @Param(value = "displayFlag") Integer displayFlag, @Param(value = "searchKey") String searchKey);
}